export const FETCH_ALL_REQUEST = 'FETCH_ALL_REQUEST';
export const FETCH_ALL_SUCCESS = 'FETCH_ALL_SUCCESS';

export const CHANGE_PURCHASE_ORDER_ITEM_QUANTITY = 'CHANGE_PURCHASE_ORDER_ITEM_QUANTITY';
export const CREATE_PURCHASE_RECORD = 'CREATE_PURCHASE_RECORD';
export const SAVE_PURCHASE_RECORD = 'SAVE_PURCHASE_RECORD';
export const CANCEL_PURCHASE_RECORD = 'CANCEL_PURCHASE_RECORD';
export const CLOSE_PURCHASE_RECORD = 'CLOSE_PURCHASE_RECORD';